# Generated by Django 5.2.7 on 2025-11-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='duration_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='hours_already_used',
            field=models.FloatField(default=0, help_text='Hours already used in this cycle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='current_cycle_used',
            field=models.FloatField(help_text='Hours used in current ELD cycle'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='current_location',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dropoff_location',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_location',
            field=models.JSONField(),
        ),
    ]
