# Generated by Django 5.2.7 on 2025-11-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_distance_km_trip_duration_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='current_cycle_used',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='current_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='distance_km',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dropoff_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='duration_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hours_already_used',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_location',
            field=models.CharField(max_length=255),
        ),
    ]
